apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/iamchoiz/k8-cicd-argocd.git
    targetRevision: HEAD
    path: app-of-apps
    helm:
      valueFiles:
        - values-eks.yaml
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=background
